-- Data/Mists/ApiManifest.lua
-- GENERATED by Tools/gen_api_manifest.py -- do not edit by hand.
--
-- Every WoW API the addon calls, measured from source. Core/ApiGuard.lua
-- probes each one at load and reports what is missing on this client.
--
-- Measured from ToonAge_Mists.toc ONLY -- the files that client actually loads.
-- Scanning the whole repository here would list retail APIs this
-- build never ships, and ApiGuard would report them missing on a
-- client where nothing calls them.
--
-- Regenerate after adding or removing call sites:
--     python Tools/gen_api_manifest.py --toc ToonAge_Mists.toc

local TA = ToonAge
TA.Data = TA.Data or {}

-- ["C_Namespace.Function"] = { files that call it }
TA.Data.ApiManifest = {
    namespaced = {
        ["C_AddOns.GetAddOnInfo"] = { "Core/Utils.lua" },
        ["C_AddOns.GetAddOnMetadata"] = { "Core/Compat/API.lua", "Core/Environment.lua", "Core/Init.lua", "Libs/WagoAnalytics/Shim.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_AddOns.IsAddOnLoaded"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_AssistedCombat.GetNextCastSpell"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_ClassTalents.GetActiveConfigID"] = { "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Container.GetContainerItemID"] = { "Core/Compat/API.lua" },
        ["C_Container.GetContainerItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Automation/VendorAssist.lua" },
        ["C_Container.GetContainerItemLink"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Mists/AutoEquip.lua" },
        ["C_Container.GetContainerNumSlots"] = { "Core/Compat/API.lua", "Modules/Automation/VendorAssist.lua", "Modules/Mists/AutoEquip.lua" },
        ["C_Container.PickupContainerItem"] = { "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua", "Modules/Mists/AutoEquip.lua" },
        ["C_Container.UseContainerItem"] = { "Modules/Automation/VendorAssist.lua" },
        ["C_Item.GetDetailedItemLevelInfo"] = { "Modules/Mists/AutoEquip.lua" },
        ["C_Item.GetItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Mists/AutoEquip.lua" },
        ["C_Item.GetItemInfoInstant"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_Item.GetItemStats"] = { "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Item.IsBound"] = { "Core/Utils.lua" },
        ["C_Item.RequestLoadItemDataByID"] = { "Core/Utils.lua" },
        ["C_Map.GetBestMapForUnit"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/Harvester.lua", "Modules/Mists/AntTrail.lua", "Modules/Mists/Arrow.lua", "Modules/Mists/CoordResolver.lua", "Modules/Mists/DeathRecovery.lua", "Modules/Mists/DevHelpers.lua", "Modules/Mists/GatherTracker.lua", "Modules/Mists/MapPins.lua", "Modules/Mists/NavHud.lua", "Modules/Mists/QuestTracker.lua" },
        ["C_Map.GetMapInfo"] = { "Modules/Mists/Arrow.lua", "Modules/Mists/DevHelpers.lua" },
        ["C_Map.GetPlayerMapPosition"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/Harvester.lua", "Modules/Mists/AntTrail.lua", "Modules/Mists/Arrow.lua", "Modules/Mists/CoordResolver.lua", "Modules/Mists/DeathRecovery.lua", "Modules/Mists/DevHelpers.lua", "Modules/Mists/GatherTracker.lua", "Modules/Mists/NavHud.lua" },
        ["C_Map.GetWorldPosFromMapPos"] = { "Core/Compat/API.lua", "Modules/Infrastructure/Harvester.lua" },
        ["C_MountJournal.GetMountIDs"] = { "Modules/Mists/AutoMount.lua" },
        ["C_MountJournal.GetMountInfoByID"] = { "Modules/Mists/AutoMount.lua" },
        ["C_MountJournal.SummonByID"] = { "Modules/Mists/AutoMount.lua" },
        ["C_QuestLog.GetInfo"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetLogIndexForQuestID"] = { "Modules/Mists/CoordResolver.lua" },
        ["C_QuestLog.GetNextWaypoint"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetNextWaypointForMap"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetNumQuestLogEntries"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetQuestObjectives"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetTitleForQuestID"] = { "Core/Utils.lua", "Modules/Mists/Arrow.lua", "Modules/Mists/MapPins.lua" },
        ["C_QuestLog.IsQuestFlaggedCompleted"] = { "Core/Utils.lua" },
        ["C_Spell.GetSpellCooldown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_Spell.GetSpellInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Spell.GetSpellName"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_Spell.GetSpellSubtext"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_SpellBook.GetNumSpellBookSkillLines"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_SpellBook.IsSpellKnown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_SuperTrack.GetSuperTrackedQuestID"] = { "Core/Utils.lua" },
        ["C_TaskQuest.GetQuestLocation"] = { "Modules/Mists/CoordResolver.lua" },
        ["C_Timer.After"] = { "Core/Init.lua", "Core/MinimapButton.lua", "Core/UI.lua", "Core/UIModern.lua", "Core/Utils.lua", "Modules/Automation/VendorAssist.lua", "Modules/Infrastructure/TestHarness.lua", "Modules/Mists/AntTrail.lua", "Modules/Mists/AutoMount.lua", "Modules/Mists/CutsceneSkip.lua", "Modules/Mists/DeathRecovery.lua", "Modules/Mists/GatherTracker.lua", "Modules/Mists/Gear.lua", "Modules/Mists/MapPins.lua", "Modules/Mists/NavHud.lua", "Modules/Mists/QuestTracker.lua" },
        ["C_Timer.NewTicker"] = { "Core/UIModern.lua", "Modules/Infrastructure/TestHarness.lua", "Modules/Mists/XPTracker.lua" },
        ["C_TooltipInfo.GetHyperlink"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_Traits.GenerateImportString"] = { "Core/Utils.lua" },
        ["C_Traits.GetConfigInfo"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_Traits.GetNodeInfo"] = { "Core/Utils.lua" },
        ["C_UnitAuras.GetBuffDataByIndex"] = { "Modules/Infrastructure/TestHarness.lua" },
    },
    globals = {
        ["GetContainerItemLink"] = { "Modules/Mists/AutoEquip.lua" },
        ["GetContainerNumSlots"] = { "Modules/Mists/AutoEquip.lua" },
        ["GetInventoryItemLink"] = { "Core/Utils.lua", "Modules/Mists/AutoEquip.lua", "Modules/Mists/DeathRecovery.lua", "Modules/Mists/Gear.lua" },
        ["GetItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Mists/AutoEquip.lua", "Modules/Mists/DeathRecovery.lua", "Modules/Mists/Gear.lua", "Modules/Mists/QuestTracker.lua" },
        ["GetItemInfoInstant"] = { "Modules/Mists/AutoEquip.lua", "Modules/Mists/GatherTracker.lua", "Modules/Mists/Gear.lua" },
        ["GetItemStats"] = { "Core/Utils.lua", "Modules/Mists/Gear.lua" },
        ["GetLootSlotLink"] = { "Modules/Mists/GatherTracker.lua" },
        ["GetNumActiveQuests"] = { "Modules/Mists/QuestTracker.lua" },
        ["GetNumAvailableQuests"] = { "Modules/Mists/QuestTracker.lua" },
        ["GetNumLootItems"] = { "Modules/Mists/GatherTracker.lua" },
        ["GetNumQuestChoices"] = { "Modules/Mists/QuestTracker.lua" },
        ["GetNumQuestLogEntries"] = { "Modules/Mists/DevHelpers.lua", "Modules/Mists/GuideContextMenu.lua", "Modules/Mists/GuideImporter.lua", "Modules/Mists/QuestTracker.lua" },
        ["GetNumTalentTabs"] = { "Core/Compat/API.lua" },
        ["GetPlayerMapPosition"] = { "Core/Compat/API.lua", "Modules/Infrastructure/Harvester.lua" },
        ["GetProfessionInfo"] = { "Core/Utils.lua" },
        ["GetProfessions"] = { "Core/Utils.lua" },
        ["GetQuestItemLink"] = { "Modules/Mists/QuestTracker.lua" },
        ["GetQuestLogTitle"] = { "Modules/Mists/DevHelpers.lua", "Modules/Mists/GuideContextMenu.lua", "Modules/Mists/GuideImporter.lua", "Modules/Mists/QuestTracker.lua" },
        ["GetRealmName"] = { "Core/Init.lua", "Modules/Mists/XPTracker.lua" },
        ["GetSpecialization"] = { "Core/UI.lua", "Modules/Mists/GuideParser.lua" },
        ["GetSpecializationInfo"] = { "Core/UI.lua", "Modules/Mists/GuideParser.lua" },
        ["GetSpellCooldown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["GetSpellInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Data/Mists/Spells.lua" },
        ["GetTalentInfo"] = { "Core/Compat/API.lua" },
        ["GetTalentTabInfo"] = { "Core/Compat/API.lua" },
        ["IsInInstance"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/Harvester.lua" },
        ["IsQuestCompletable"] = { "Modules/Mists/QuestTracker.lua" },
        ["IsSpellKnown"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Data/Mists/Spells.lua" },
        ["SelectActiveQuest"] = { "Modules/Mists/QuestTracker.lua" },
        ["SelectAvailableQuest"] = { "Modules/Mists/QuestTracker.lua" },
        ["UnitPosition"] = { "Core/Compat/API.lua", "Modules/Infrastructure/Harvester.lua" },
        ["geterrorhandler"] = { "Core/Init.lua", "Modules/Infrastructure/ErrorLog.lua" },
        ["hooksecurefunc"] = { "Core/Init.lua", "Modules/Mists/AntTrail.lua", "Modules/Mists/GatherTracker.lua", "Modules/Mists/Gear.lua", "Modules/Mists/MapPins.lua" },
        ["seterrorhandler"] = { "Modules/Infrastructure/ErrorLog.lua" },
    },
}
