-- Data/TBC/ApiManifest.lua
-- GENERATED by Tools/gen_api_manifest.py -- do not edit by hand.
--
-- Every WoW API the addon calls, measured from source. Core/ApiGuard.lua
-- probes each one at load and reports what is missing on this client.
--
-- Measured from ToonAge_TBC.toc ONLY -- the files that client actually loads.
-- Scanning the whole repository here would list retail APIs this
-- build never ships, and ApiGuard would report them missing on a
-- client where nothing calls them.
--
-- Regenerate after adding or removing call sites:
--     python Tools/gen_api_manifest.py --toc ToonAge_TBC.toc

local TA = ToonAge
TA.Data = TA.Data or {}

-- ["C_Namespace.Function"] = { files that call it }
TA.Data.ApiManifest = {
    namespaced = {
        ["C_AddOns.GetAddOnInfo"] = { "Core/Utils.lua" },
        ["C_AddOns.GetAddOnMetadata"] = { "Core/Compat/API.lua", "Core/Environment.lua", "Core/Init.lua", "Libs/WagoAnalytics/Shim.lua", "Modules/Infrastructure/Settings.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_AddOns.IsAddOnLoaded"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_AssistedCombat.GetNextCastSpell"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_BattleNet.GetAccountInfoByGUID"] = { "Modules/Automation/AutoQuest.lua" },
        ["C_ClassTalents.GetActiveConfigID"] = { "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Container.GetContainerItemID"] = { "Core/Compat/API.lua" },
        ["C_Container.GetContainerItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Automation/VendorAssist.lua", "Modules/TBC/PetCare.lua" },
        ["C_Container.GetContainerItemLink"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/TBC/AutoEquip.lua" },
        ["C_Container.GetContainerNumSlots"] = { "Core/Compat/API.lua", "Modules/Automation/VendorAssist.lua", "Modules/TBC/AutoEquip.lua" },
        ["C_Container.PickupContainerItem"] = { "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua", "Modules/TBC/AutoEquip.lua" },
        ["C_Container.UseContainerItem"] = { "Modules/Automation/VendorAssist.lua" },
        ["C_FriendList.IsFriend"] = { "Modules/Automation/AutoQuest.lua" },
        ["C_GossipInfo.GetActiveQuests"] = { "Modules/Automation/AutoQuest.lua" },
        ["C_GossipInfo.GetAvailableQuests"] = { "Modules/Automation/AutoQuest.lua" },
        ["C_GossipInfo.SelectActiveQuest"] = { "Modules/Automation/AutoQuest.lua" },
        ["C_GossipInfo.SelectAvailableQuest"] = { "Modules/Automation/AutoQuest.lua" },
        ["C_Item.GetDetailedItemLevelInfo"] = { "Modules/TBC/AutoEquip.lua" },
        ["C_Item.GetItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Automation/AutoQuest.lua", "Modules/TBC/AutoEquip.lua" },
        ["C_Item.GetItemInfoInstant"] = { "Data/TBC/TBCTalentHit.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Item.GetItemStats"] = { "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Item.IsBound"] = { "Core/Utils.lua" },
        ["C_Item.RequestLoadItemDataByID"] = { "Core/Utils.lua" },
        ["C_Map.GetBestMapForUnit"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/Harvester.lua" },
        ["C_Map.GetPlayerMapPosition"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/Harvester.lua" },
        ["C_Map.GetWorldPosFromMapPos"] = { "Core/Compat/API.lua", "Modules/Infrastructure/Harvester.lua" },
        ["C_QuestLog.GetInfo"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetNextWaypoint"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetNextWaypointForMap"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetNumQuestLogEntries"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetQuestObjectives"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetTitleForQuestID"] = { "Core/Utils.lua" },
        ["C_QuestLog.IsQuestFlaggedCompleted"] = { "Core/Utils.lua" },
        ["C_Spell.GetSpellCooldown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_Spell.GetSpellInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Spell.GetSpellName"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_Spell.GetSpellSubtext"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_SpellBook.GetNumSpellBookSkillLines"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_SpellBook.IsSpellKnown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_SuperTrack.GetSuperTrackedQuestID"] = { "Core/Utils.lua" },
        ["C_Timer.After"] = { "Core/Init.lua", "Core/MinimapButton.lua", "Core/UI.lua", "Core/UIModern.lua", "Core/Utils.lua", "Modules/Automation/VendorAssist.lua", "Modules/Infrastructure/TestHarness.lua", "Modules/TBC/Spells.lua" },
        ["C_Timer.NewTicker"] = { "Core/UIModern.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_TooltipInfo.GetHyperlink"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_Traits.GenerateImportString"] = { "Core/Utils.lua" },
        ["C_Traits.GetConfigInfo"] = { "Modules/Infrastructure/TestHarness.lua" },
        ["C_Traits.GetNodeInfo"] = { "Core/Utils.lua" },
        ["C_UnitAuras.GetBuffDataByIndex"] = { "Modules/Infrastructure/TestHarness.lua" },
    },
    globals = {
        ["GetContainerItemLink"] = { "Modules/TBC/AutoEquip.lua" },
        ["GetContainerNumSlots"] = { "Modules/TBC/AutoEquip.lua" },
        ["GetInventoryItemLink"] = { "Core/SkillScan.lua", "Core/TBCUtils.lua", "Core/Utils.lua", "Data/TBC/TBCTalentHit.lua", "Modules/TBC/AutoEquip.lua", "Modules/TBC/Gear.lua", "Modules/TBC/PvPAdvisor.lua" },
        ["GetItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/TBC/AutoEquip.lua" },
        ["GetItemStats"] = { "Core/Utils.lua" },
        ["GetNumTalentTabs"] = { "Core/Compat/API.lua" },
        ["GetPlayerMapPosition"] = { "Core/Compat/API.lua", "Modules/Infrastructure/Harvester.lua" },
        ["GetProfessionInfo"] = { "Core/Utils.lua" },
        ["GetProfessions"] = { "Core/Utils.lua" },
        ["GetRealmName"] = { "Core/Init.lua" },
        ["GetSpecialization"] = { "Core/UI.lua" },
        ["GetSpecializationInfo"] = { "Core/UI.lua" },
        ["GetSpellCooldown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["GetSpellInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["GetTalentInfo"] = { "Core/Compat/API.lua" },
        ["GetTalentTabInfo"] = { "Core/Compat/API.lua" },
        ["IsInInstance"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Infrastructure/Harvester.lua" },
        ["IsSpellKnown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["UnitDefense"] = { "Core/TBCStats.lua" },
        ["UnitPosition"] = { "Core/Compat/API.lua", "Modules/Infrastructure/Harvester.lua" },
        ["geterrorhandler"] = { "Core/Init.lua", "Modules/Infrastructure/ErrorLog.lua" },
        ["hooksecurefunc"] = { "Core/Init.lua" },
        ["seterrorhandler"] = { "Modules/Infrastructure/ErrorLog.lua" },
    },
}
