-- Data/Forever/ApiManifest.lua
-- GENERATED by Tools/gen_api_manifest.py -- do not edit by hand.
--
-- Every WoW API the addon calls, measured from source. Core/ApiGuard.lua
-- probes each one at load and reports what is missing on this client.
--
-- Measured from ToonAge_Camelot.toc ONLY -- the files that client actually loads.
-- Scanning the whole repository here would list retail APIs this
-- build never ships, and ApiGuard would report them missing on a
-- client where nothing calls them.
--
-- Regenerate after adding or removing call sites:
--     python Tools/gen_api_manifest.py --toc ToonAge_Camelot.toc

local TA = ToonAge
TA.Data = TA.Data or {}

-- ["C_Namespace.Function"] = { files that call it }
TA.Data.ApiManifest = {
    namespaced = {
        ["C_AddOns.GetAddOnInfo"] = { "Core/Utils.lua" },
        ["C_AddOns.GetAddOnMetadata"] = { "Core/Compat/API.lua", "Core/Environment.lua", "Core/Init.lua", "Libs/WagoAnalytics/Shim.lua", "Modules/Infrastructure/Settings.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_AddOns.IsAddOnLoaded"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_AssistedCombat.GetNextCastSpell"] = { "Modules/Forever/DataHarvester.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_ClassTalents.GetActiveConfigID"] = { "Core/Utils.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/SessionCheck.lua", "Modules/Forever/Talents.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Container.GetContainerItemID"] = { "Core/Compat/API.lua" },
        ["C_Container.GetContainerItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_Container.GetContainerItemLink"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Gear.lua" },
        ["C_Container.GetContainerNumSlots"] = { "Core/Compat/API.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Gear.lua" },
        ["C_Container.PickupContainerItem"] = { "Core/Utils.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Item.GetItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Farming/GatherTracker.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Gear.lua", "Modules/Forever/SessionCheck.lua" },
        ["C_Item.GetItemInfoInstant"] = { "Modules/Farming/GatherTracker.lua", "Modules/Forever/Character.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Scrolls.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Item.GetItemNameByID"] = { "Modules/Forever/SessionCheck.lua" },
        ["C_Item.GetItemStats"] = { "Core/Utils.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Gear.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Item.IsBound"] = { "Core/Utils.lua" },
        ["C_Item.RequestLoadItemDataByID"] = { "Core/Utils.lua" },
        ["C_Map.GetBestMapForUnit"] = { "Core/Utils.lua", "Modules/Automation/DeathRecovery.lua", "Modules/Farming/GatherTracker.lua", "Modules/Forever/DataHarvester.lua", "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_Map.GetMapInfo"] = { "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_Map.GetPlayerMapPosition"] = { "Core/Utils.lua", "Modules/Automation/DeathRecovery.lua", "Modules/Farming/GatherTracker.lua", "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_MerchantFrame.GetItemInfo"] = { "Modules/Forever/Gear.lua" },
        ["C_MerchantFrame.GetItemLink"] = { "Modules/Forever/Gear.lua" },
        ["C_PaperDollInfo.OffhandHasWeapon"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_QuestLog.GetInfo"] = { "Core/Utils.lua", "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_QuestLog.GetNextWaypoint"] = { "Core/Utils.lua", "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_QuestLog.GetNextWaypointForMap"] = { "Core/Utils.lua", "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_QuestLog.GetNumQuestLogEntries"] = { "Core/Utils.lua", "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_QuestLog.GetQuestObjectives"] = { "Core/Utils.lua" },
        ["C_QuestLog.GetTitleForQuestID"] = { "Core/Utils.lua", "Modules/Infrastructure/CoordHarvester.lua" },
        ["C_QuestLog.IsQuestFlaggedCompleted"] = { "Core/Utils.lua" },
        ["C_SkillInfo.GetNumSkillLines"] = { "Modules/Forever/Character.lua", "Modules/Forever/DataHarvester.lua" },
        ["C_SkillInfo.GetSelectedSkill"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_SkillInfo.GetSkillLineInfo"] = { "Modules/Forever/Character.lua", "Modules/Forever/DataHarvester.lua" },
        ["C_SkillInfo.GetSkillLineInfoByID"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Scrolls.lua" },
        ["C_Spell.GetSpellCooldown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["C_Spell.GetSpellInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Rotation.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Spell.GetSpellLevelLearned"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Rotation.lua" },
        ["C_Spell.GetSpellName"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Forever/CastLog.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Rotation.lua", "Modules/Forever/Talents.lua" },
        ["C_Spell.GetSpellPowerCost"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_Spell.GetSpellRank"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_Spell.GetSpellSubtext"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Rotation.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Spell.GetSpellTexture"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_Spell.RequestLoadSpellData"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_SpellBook.GetNumSpellBookSkillLines"] = { "Modules/Forever/CastLog.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Rotation.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_SpellBook.GetSpellBookItemInfo"] = { "Modules/Forever/CastLog.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Rotation.lua" },
        ["C_SpellBook.GetSpellBookSkillLineInfo"] = { "Modules/Forever/CastLog.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Rotation.lua" },
        ["C_SpellBook.IsSpellKnown"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Forever/Gear.lua" },
        ["C_SuperTrack.GetSuperTrackedQuestID"] = { "Core/Utils.lua" },
        ["C_Timer.After"] = { "Core/Init.lua", "Core/MinimapButton.lua", "Core/UI.lua", "Core/UIModern.lua", "Core/Utils.lua", "Modules/Automation/DeathRecovery.lua", "Modules/Farming/GatherTracker.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Gear.lua", "Modules/Forever/Scrolls.lua", "Modules/Forever/SessionCheck.lua", "Modules/Infrastructure/CoordHarvester.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Timer.NewTicker"] = { "Core/UIModern.lua", "Modules/Infrastructure/TestHarness.lua", "Modules/Progression/XPTracker.lua" },
        ["C_TooltipInfo.GetHyperlink"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Scrolls.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_TooltipInfo.GetSpellByID"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_TooltipInfo.GetTrainerService"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_TradeSkillUI.GetProfessionInfoBySkillLineID"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Scrolls.lua" },
        ["C_Traits.GenerateImportString"] = { "Core/Utils.lua" },
        ["C_Traits.GetConditionInfo"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_Traits.GetConfigInfo"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/SessionCheck.lua", "Modules/Forever/Talents.lua", "Modules/Infrastructure/TestHarness.lua" },
        ["C_Traits.GetDefinitionInfo"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Talents.lua" },
        ["C_Traits.GetEntryInfo"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Talents.lua" },
        ["C_Traits.GetNodeInfo"] = { "Core/Utils.lua", "Modules/Forever/DataHarvester.lua", "Modules/Forever/Talents.lua" },
        ["C_Traits.GetTreeCurrencyInfo"] = { "Modules/Forever/SessionCheck.lua", "Modules/Forever/Talents.lua" },
        ["C_Traits.GetTreeInfo"] = { "Modules/Forever/DataHarvester.lua" },
        ["C_Traits.GetTreeNodes"] = { "Modules/Forever/DataHarvester.lua", "Modules/Forever/Talents.lua" },
        ["C_UnitAuras.GetAuraDataByIndex"] = { "Modules/Forever/CastLog.lua" },
        ["C_UnitAuras.GetBuffDataByIndex"] = { "Modules/Forever/Scrolls.lua", "Modules/Infrastructure/TestHarness.lua" },
    },
    globals = {
        ["GetAverageItemLevel"] = { "Modules/Automation/DeathRecovery.lua" },
        ["GetInventoryItemLink"] = { "Core/Utils.lua" },
        ["GetItemInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["GetItemStats"] = { "Core/Utils.lua" },
        ["GetNumSkillLines"] = { "Modules/Forever/Scrolls.lua" },
        ["GetNumTalentTabs"] = { "Core/Compat/API.lua" },
        ["GetProfessionInfo"] = { "Core/Utils.lua", "Modules/Forever/DataHarvester.lua" },
        ["GetProfessions"] = { "Core/Utils.lua", "Modules/Forever/DataHarvester.lua" },
        ["GetRealmName"] = { "Core/Init.lua", "Modules/Progression/XPTracker.lua" },
        ["GetSkillLineInfo"] = { "Modules/Forever/Scrolls.lua" },
        ["GetSpecialization"] = { "Core/UI.lua" },
        ["GetSpecializationInfo"] = { "Core/UI.lua" },
        ["GetSpellCooldown"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["GetSpellInfo"] = { "Core/Compat/API.lua", "Core/Utils.lua" },
        ["GetTalentInfo"] = { "Core/Compat/API.lua" },
        ["GetTalentTabInfo"] = { "Core/Compat/API.lua" },
        ["IsSpellKnown"] = { "Core/Compat/API.lua", "Core/Utils.lua", "Modules/Forever/DataHarvester.lua" },
        ["UnitDefense"] = { "Modules/Forever/DataHarvester.lua" },
        ["geterrorhandler"] = { "Core/Init.lua", "Modules/Infrastructure/ErrorLog.lua" },
        ["hooksecurefunc"] = { "Core/Init.lua", "Modules/Farming/GatherTracker.lua", "Modules/Forever/Gear.lua", "Modules/Forever/WorldRefresh.lua" },
        ["issecretvalue"] = { "Modules/Forever/Gear.lua", "Modules/Forever/Talents.lua" },
        ["seterrorhandler"] = { "Modules/Infrastructure/ErrorLog.lua" },
    },
}
