-- ToonAge/Data/Forever/Racials.lua
-- GENERATED by Tools/gen_forever_data.lua from the Forever harvest -- do not edit by hand.
--
-- Racial abilities per race and faction, tooltips verbatim from the client.
-- Measured on the Forever client (interface 16001); 44 records.
-- Regenerate after a harvest: lua Tools/gen_forever_data.lua <ToonAge.lua saved file> <addon root>

local TA = ToonAge
TA.Data = TA.Data or {}

TA.Data.ForeverRacials = {
    ["Dwarf"] = {
        ["Alliance"] = {
            { id = 1259721, name = "Big Game Hunter", passive = true, tooltip = "Passive | Damage dealt versus Beasts increased by 5%." },
            { id = 2481, name = "Find Treasure", tooltip = "Instant | Allows the dwarf to sense nearby treasure, making it appear on the minimap.  Lasts until canceled." },
            { id = 1259719, name = "Mace Specialization", passive = true, tooltip = "Passive | Increases your critical strike chance with all spells and attacks by 1% while you have a mace or two-handed mace equipped." },
            { id = 20594, name = "Stoneform", cooldown = 180, removes = { "bleed", "poison", "disease" }, tooltip = "Instant | 3 min cooldown | Instantly removes and grants immunity to all Bleed, Poison, and Disease effects, and reduces all Physical damage taken by 10% for 8 sec." },
        },
    },
    ["Gnome"] = {
        ["Alliance"] = {
            { id = 20593, name = "Engineering Specialization", passive = true, tooltip = "Passive | Your gnomish ingenuity reduces the rate of engineering devices failing or backfiring when you use them by 20%." },
            { id = 20589, name = "Escape Artist", cooldown = 120, removes = { "snare" }, tooltip = "Instant | 2 min cooldown | Instantly escape the effects of any movement impairing effect and gain immunity to those effects for 3 sec." },
            { id = 1259812, name = "Eureka!", classes = { "ROGUE" }, cooldown = 120, tooltip = "Instant | 2 min cooldown | Your next 3 damaging abilities have their Energy cost reduced by 10% and deal 10% more damage." },
            { id = 1259813, name = "Eureka!", classes = { "WARRIOR" }, cooldown = 120, tooltip = "Instant | 2 min cooldown | Your next 3 damaging abilities have their Rage cost reduced by 10% and deal 10% more damage." },
            { id = 1259823, name = "Eureka!", classes = { "PRIEST" }, cooldown = 120, tooltip = "Instant | 2 min cooldown | Your next 3 damaging or healing abilities have their Mana cost reduced by 10% and deal 10% more damage or healing." },
            { id = 20591, name = "Expansive Mind", passive = true, classes = { "PRIEST" }, tooltip = "Passive | Maximum Mana increased by 5%." },
            { id = 1259802, name = "Expansive Mind", passive = true, classes = { "WARRIOR" }, tooltip = "Passive | Maximum Rage increased by 5%." },
            { id = 1259803, name = "Expansive Mind", passive = true, classes = { "ROGUE" }, tooltip = "Passive | Maximum Energy increased by 5%." },
        },
    },
    ["Human"] = {
        ["Alliance"] = {
            { id = 20600, name = "Perception", cooldown = 180, detects = "stealth", tooltip = "Instant | 3 min cooldown | Dramatically increases stealth detection for 20 sec." },
            { id = 20597, name = "Sword Specialization", passive = true, tooltip = "Passive | Increases your critical strike chance with all spells and attacks by 2% while you have a sword or two-handed sword equipped." },
            { id = 20598, name = "The Human Spirit", passive = true, tooltip = "Passive | Spirit increased by 5%." },
            { id = 1259718, name = "Will to Survive", cooldown = 180, removes = { "stun" }, tooltip = "Instant | 3 min cooldown | Instantly removes all Stun effects." },
        },
    },
    ["NightElf"] = {
        ["Alliance"] = {
            { id = 1259799, name = "Elune's Light", cooldown = 180, burst = true, tooltip = "Instant | 3 min cooldown | Increases your critical strike chance with all spells and attacks by 10% for 15 sec." },
            { id = 20582, name = "Quickness", passive = true, tooltip = "Passive | Dodge chance increased by 1% and movement speed increased by 2%. Night Elf Rogues and Druids are harder to detect in Stealth as if they were 1 level higher." },
            { id = 20580, name = "Shadowmeld", cooldown = 10, tooltip = "Instant | 10 sec cooldown | Activate to slip into the shadows, reducing the chance for enemies to detect your presence. Lasts until cancelled or upon moving. Using this ability in combat discourages enemies from attacking you, but increases the cooldown to 2 min." },
            { id = 20585, name = "Wisp Spirit", passive = true, tooltip = "Passive | Transform into a wisp upon death, increasing movement speed by 75%." },
        },
    },
    ["Orc"] = {
        ["Horde"] = {
            { id = 20574, name = "Axe Specialization", passive = true, tooltip = "Passive | Increases your critical strike chance with all spells and abilities by 1% while you have an axe or a two-handed axe equipped." },
            { id = 20572, name = "Blood Fury", cooldown = 120, burst = true, tooltip = "Instant | 2 min cooldown | Increases Attack Power and Spell Power by 10% for 15 sec." },
            { id = 20573, name = "Hardiness", passive = true, removes = { "stun" }, tooltip = "Passive | Duration of Stun effects on you reduced by 20%." },
            { id = 1299026, name = "Shatter Curse", cooldown = 180, removes = { "curse" }, tooltip = "Instant | 3 min cooldown | Instantly removes and grants immunity to all Curses and Banes, and reduces all Magical damage taken by 15% for 8 sec." },
        },
    },
    ["Scourge"] = {
        ["Horde"] = {
            { id = 20577, name = "Cannibalize", cooldown = 120, tooltip = "5 yd range | Instant | 2 min cooldown | When activated, regenerates 7% of total Health and 7% of total Mana every 2 sec for 10 sec. Only works on Humanoid or Undead corpses within 5 yds. Any movement, action, or damage taken while Cannibalizing will cancel the effect." },
            { id = 1260189, name = "Touch of the Grave", passive = true, classes = { "PALADIN" }, tooltip = "Passive | Your spells and attacks have a 5% chance to drain Health from the target, up to 5% of your maximum Health." },
            { id = 1260201, name = "Touch of the Grave", passive = true, classes = { "MAGE" }, tooltip = "Passive | Your spells and attacks have a 10% chance to drain Health from the target, up to 5% of your maximum Health." },
            { id = 5227, name = "Underwater Breathing", passive = true, tooltip = "Passive | Underwater breath lasts 300% longer than normal." },
            { id = 7744, name = "Will of the Forsaken", cooldown = 120, removes = { "fear", "charm", "sleep" }, tooltip = "Instant | 2 min cooldown | Instantly removes all Charm, Fear and Sleep effects." },
        },
    },
    ["Skyborne"] = {
        ["Alliance"] = {
            { id = 1259707, name = "Elemental Insight", passive = true, tooltip = "Passive | Damage dealt versus Elementals increased by 5%." },
            { id = 1259705, name = "Read Ley Line", cooldown = 120, tooltip = "2 sec cast | 2 min cooldown | Attempt to tap into the power of a nearby ley line, increasing your Health and Mana regeneration by 100%. Lasts 15 sec if no ley line is nearby, and 15 min if one is found." },
            { id = 1259416, name = "Walk on Air", cooldown = 120, tooltip = "Instant | 2 min cooldown | Glide downward through the air for 10 sec while controlling your direction of travel." },
            { id = 1259710, name = "Wind Blessed", passive = true, tooltip = "Passive | Increases your spellcasting, melee, and ranged Haste by 1%." },
        },
        ["Horde"] = {
            { id = 1259707, name = "Elemental Insight", passive = true, tooltip = "Passive | Damage dealt versus Elementals increased by 5%." },
            { id = 1259686, name = "Skysight", cooldown = 120, tooltip = "0.5 sec cast | 2 min cooldown | Attempt to draw power from a convergence of elements and receive its blessing, increasing your movement and mounted movement speeds by 10%. Lasts 30 sec if no elemental convergence is nearby, and 15 min if one is found.  " },
            { id = 1259416, name = "Walk on Air", cooldown = 120, tooltip = "Instant | 2 min cooldown | Glide downward through the air for 10 sec while controlling your direction of travel." },
            { id = 1259710, name = "Wind Blessed", passive = true, tooltip = "Passive | Increases your spellcasting, melee, and ranged Haste by 1%." },
        },
    },
    ["Tauren"] = {
        ["Horde"] = {
            { id = 20552, name = "Cultivation", tooltip = "Instant | Cultivate a nearby herb, growing a duplicate you can harvest without requiring Herbalism skill. Each herb may only be cultivated once." },
            { id = 20550, name = "Endurance", passive = true, tooltip = "Passive | Total Health increased by 5% and chance to hit increased by 1%." },
            { id = 1259918, name = "Plainsrunning", passive = true, tooltip = "Passive | Gain 1% increased movement speed every 5 sec spent moving, up to a maximum of 30% increase. Taking damage or standing still will reduce this effect." },
            { id = 20549, name = "War Stomp", cooldown = 120, inflicts = { "stun" }, tooltip = "0.5 sec cast | 2 min cooldown | Stuns up to 5 enemies within 8 yds for 2 sec." },
        },
    },
    ["Troll"] = {
        ["Horde"] = {
            { id = 20557, name = "Beast Slaying", passive = true, tooltip = "Passive | Damage dealt versus Beasts increased by 5%." },
            { id = 20554, name = "Berserking", cooldown = 180, burst = true, tooltip = "Instant | 3 min cooldown | Increases your spellcasting and attack speed by 10% for 10 sec." },
            { id = 20555, name = "Regeneration", passive = true, tooltip = "Passive | Health regeneration rate increased by 10%. In addition, 10% of total Health regeneration will continue during combat." },
        },
    },
}
