-- ToonAge/Data/Forever/SpellRanks.lua
-- GENERATED by Tools/gen_forever_data.lua from the Forever harvest -- do not edit by hand.
--
-- Every trainable spell the client reports, by spell name, ordered by trained level (the Harvest tab's spell catalog).
-- Measured on the Forever client (interface 16001); 81 records.
-- verified = true is the Forever 1.60.1 spellbook and catalog confirmation:
-- rogue ranks named there, and mage ranks whose id and learn level match Era through level 42.
-- Regenerate after a harvest: lua Tools/gen_forever_data.lua <ToonAge.lua saved file> <addon root>

local TA = ToonAge
TA.Data = TA.Data or {}

TA.Data.ForeverSpellRanks = {
    ["Amplify Magic"] = { { id = 1008, n = 1, learned = 18, verified = true }, { id = 8455, n = 2, learned = 30, verified = true } },
    ["Arcane Explosion"] = { { id = 1449, n = 1, learned = 14, verified = true }, { id = 8437, n = 2, learned = 22, verified = true }, { id = 8438, n = 3, learned = 30, verified = true }, { id = 8439, n = 4, learned = 38, verified = true } },
    ["Arcane Intellect"] = { { id = 1459, n = 1, learned = 1, verified = true }, { id = 1460, n = 2, learned = 14, verified = true }, { id = 1461, n = 3, learned = 28, verified = true } },
    ["Arcane Missiles"] = { { id = 5143, n = 1, learned = 8, verified = true }, { id = 5144, n = 2, learned = 16, verified = true }, { id = 5145, n = 3, learned = 24, verified = true }, { id = 8416, n = 4, learned = 32, verified = true }, { id = 8417, n = 5, learned = 40, verified = true } },
    ["Backstab"] = { { id = 53, n = 1, learned = 4, verified = true } },
    ["Blizzard"] = { { id = 10, n = 1, learned = 20, verified = true }, { id = 6141, n = 2, learned = 28, verified = true }, { id = 8427, n = 3, learned = 36, verified = true } },
    ["Cone of Cold"] = { { id = 120, n = 1, learned = 26, verified = true }, { id = 8492, n = 2, learned = 34, verified = true } },
    ["Conjure Food"] = { { id = 587, n = 1, learned = 6, verified = true }, { id = 597, n = 2, learned = 12, verified = true }, { id = 990, n = 3, learned = 22, verified = true }, { id = 6129, n = 4, learned = 32, verified = true } },
    ["Conjure Water"] = { { id = 5504, n = 1, learned = 4, verified = true }, { id = 5505, n = 2, learned = 10, verified = true }, { id = 5506, n = 3, learned = 20, verified = true }, { id = 6127, n = 4, learned = 30, verified = true } },
    ["Dampen Magic"] = { { id = 604, n = 1, learned = 12, verified = true }, { id = 8450, n = 2, learned = 24, verified = true }, { id = 8451, n = 3, learned = 36, verified = true } },
    ["Eviscerate"] = { { id = 2098, n = 1, learned = 1, verified = true } },
    ["Fire Blast"] = { { id = 2136, n = 1, learned = 6, verified = true }, { id = 2137, n = 2, learned = 14, verified = true }, { id = 2138, n = 3, learned = 22, verified = true }, { id = 8412, n = 4, learned = 30, verified = true }, { id = 8413, n = 5, learned = 38, verified = true } },
    ["Fire Ward"] = { { id = 543, n = 1, learned = 20, verified = true }, { id = 8457, n = 2, learned = 30, verified = true }, { id = 8458, n = 3, learned = 40, verified = true } },
    ["Fireball"] = { { id = 133, n = 1, learned = 1, verified = true }, { id = 143, n = 2, learned = 6, verified = true }, { id = 145, n = 3, learned = 12, verified = true }, { id = 3140, n = 4, learned = 18, verified = true }, { id = 8400, n = 5, learned = 24, verified = true }, { id = 8401, n = 6, learned = 30, verified = true }, { id = 8402, n = 7, learned = 36, verified = true } },
    ["Flamestrike"] = { { id = 2120, n = 1, learned = 16, verified = true }, { id = 2121, n = 2, learned = 24, verified = true }, { id = 8422, n = 3, learned = 32, verified = true }, { id = 8423, n = 4, learned = 40, verified = true } },
    ["Frost Armor"] = { { id = 168, n = 1, learned = 1, verified = true }, { id = 7300, n = 2, learned = 10, verified = true }, { id = 7301, n = 3, learned = 20, verified = true } },
    ["Frost Nova"] = { { id = 122, n = 1, learned = 10, verified = true }, { id = 865, n = 2, learned = 26, verified = true }, { id = 6131, n = 3, learned = 40, verified = true } },
    ["Frost Ward"] = { { id = 6143, n = 1, learned = 22, verified = true }, { id = 8461, n = 2, learned = 32, verified = true }, { id = 8462, n = 3, learned = 42, verified = true } },
    ["Frostbolt"] = { { id = 116, n = 1, learned = 4, verified = true }, { id = 205, n = 2, learned = 8, verified = true }, { id = 837, n = 3, learned = 14, verified = true }, { id = 7322, n = 4, learned = 20, verified = true }, { id = 8406, n = 5, learned = 26, verified = true }, { id = 8407, n = 6, learned = 32, verified = true }, { id = 8408, n = 7, learned = 38, verified = true } },
    ["Gouge"] = { { id = 1776, n = 1, learned = 6, verified = true } },
    ["Ice Armor"] = { { id = 7302, n = 1, learned = 30, verified = true }, { id = 7320, n = 2, learned = 40, verified = true } },
    ["Mana Shield"] = { { id = 1463, n = 1, learned = 20, verified = true }, { id = 8494, n = 2, learned = 28, verified = true }, { id = 8495, n = 3, learned = 36, verified = true } },
    ["Scorch"] = { { id = 2948, n = 1, learned = 22, verified = true }, { id = 8444, n = 2, learned = 28, verified = true }, { id = 8445, n = 3, learned = 34, verified = true }, { id = 8446, n = 4, learned = 40, verified = true } },
    ["Sinister Strike"] = { { id = 1752, n = 1, learned = 1, verified = true }, { id = 1757, n = 2, learned = 6, verified = true } },
    ["Stealth"] = { { id = 1784, n = 1, learned = 1, verified = true } },
    ["Throw"] = { { id = 2764, n = 1, learned = 1, verified = true } },
}
