-- ToonAge/Data/Forever/SpellRanks.lua
-- GENERATED by Tools/gen_forever_data.lua from the Forever harvest -- do not edit by hand.
--
-- Every trainable spell the client reports, by spell name, ordered by trained level (the Harvest tab's spell catalog).
-- Measured on the Forever client (interface 16001); 74 records.
-- Regenerate after a harvest: lua Tools/gen_forever_data.lua <ToonAge.lua saved file> <addon root>

local TA = ToonAge
TA.Data = TA.Data or {}

TA.Data.ForeverSpellRanks = {
    ["Amplify Magic"] = { { id = 1008, n = 1, learned = 18 }, { id = 8455, n = 2, learned = 30 } },
    ["Arcane Explosion"] = { { id = 1449, n = 1, learned = 14 }, { id = 8437, n = 2, learned = 22 }, { id = 8438, n = 3, learned = 30 }, { id = 8439, n = 4, learned = 38 } },
    ["Arcane Intellect"] = { { id = 1459, n = 1, learned = 1 }, { id = 1460, n = 2, learned = 14 }, { id = 1461, n = 3, learned = 28 } },
    ["Arcane Missiles"] = { { id = 5143, n = 1, learned = 8 }, { id = 5144, n = 2, learned = 16 }, { id = 5145, n = 3, learned = 24 }, { id = 8416, n = 4, learned = 32 }, { id = 8417, n = 5, learned = 40 } },
    ["Blizzard"] = { { id = 10, n = 1, learned = 20 }, { id = 6141, n = 2, learned = 28 }, { id = 8427, n = 3, learned = 36 } },
    ["Cone of Cold"] = { { id = 120, n = 1, learned = 26 }, { id = 8492, n = 2, learned = 34 } },
    ["Conjure Food"] = { { id = 587, n = 1, learned = 6 }, { id = 597, n = 2, learned = 12 }, { id = 990, n = 3, learned = 22 }, { id = 6129, n = 4, learned = 32 } },
    ["Conjure Water"] = { { id = 5504, n = 1, learned = 4 }, { id = 5505, n = 2, learned = 10 }, { id = 5506, n = 3, learned = 20 }, { id = 6127, n = 4, learned = 30 } },
    ["Dampen Magic"] = { { id = 604, n = 1, learned = 12 }, { id = 8450, n = 2, learned = 24 }, { id = 8451, n = 3, learned = 36 } },
    ["Fire Blast"] = { { id = 2136, n = 1, learned = 6 }, { id = 2137, n = 2, learned = 14 }, { id = 2138, n = 3, learned = 22 }, { id = 8412, n = 4, learned = 30 }, { id = 8413, n = 5, learned = 38 } },
    ["Fire Ward"] = { { id = 543, n = 1, learned = 20 }, { id = 8457, n = 2, learned = 30 }, { id = 8458, n = 3, learned = 40 } },
    ["Fireball"] = { { id = 133, n = 1, learned = 1 }, { id = 143, n = 2, learned = 6 }, { id = 145, n = 3, learned = 12 }, { id = 3140, n = 4, learned = 18 }, { id = 8400, n = 5, learned = 24 }, { id = 8401, n = 6, learned = 30 }, { id = 8402, n = 7, learned = 36 } },
    ["Flamestrike"] = { { id = 2120, n = 1, learned = 16 }, { id = 2121, n = 2, learned = 24 }, { id = 8422, n = 3, learned = 32 }, { id = 8423, n = 4, learned = 40 } },
    ["Frost Armor"] = { { id = 168, n = 1, learned = 1 }, { id = 7300, n = 2, learned = 10 }, { id = 7301, n = 3, learned = 20 } },
    ["Frost Nova"] = { { id = 122, n = 1, learned = 10 }, { id = 865, n = 2, learned = 26 }, { id = 6131, n = 3, learned = 40 } },
    ["Frost Ward"] = { { id = 6143, n = 1, learned = 22 }, { id = 8461, n = 2, learned = 32 }, { id = 8462, n = 3, learned = 42 } },
    ["Frostbolt"] = { { id = 116, n = 1, learned = 4 }, { id = 205, n = 2, learned = 8 }, { id = 837, n = 3, learned = 14 }, { id = 7322, n = 4, learned = 20 }, { id = 8406, n = 5, learned = 26 }, { id = 8407, n = 6, learned = 32 }, { id = 8408, n = 7, learned = 38 } },
    ["Ice Armor"] = { { id = 7302, n = 1, learned = 30 }, { id = 7320, n = 2, learned = 40 } },
    ["Mana Shield"] = { { id = 1463, n = 1, learned = 20 }, { id = 8494, n = 2, learned = 28 }, { id = 8495, n = 3, learned = 36 } },
    ["Scorch"] = { { id = 2948, n = 1, learned = 22 }, { id = 8444, n = 2, learned = 28 }, { id = 8445, n = 3, learned = 34 }, { id = 8446, n = 4, learned = 40 } },
}
