#!/usr/bin/env python3
"""
CharacterAdvisor -- WoWDB Quest Crawler
========================================
Parses all page_N.html files from a local wowdb quest listing dump and
produces two outputs:

  quests_database.csv  -- flat CSV: questID, name, minLevel, maxLevel, category
  quests_database.lua  -- Lua lookup table: CA.QuestDB[questID] = {...}

Usage:
    python crawl_wowdb_quests.py

Edit HTML_DIR and OUTPUT_DIR if needed.
"""

import os
import re
import csv
import html as html_module
import sys
from pathlib import Path

HTML_DIR   = Path(r"E:\OneDrive\Desktop\wowdb\html_pages")
OUTPUT_DIR = Path(r"E:\OneDrive\Desktop\wowdb")


# ── Row parser ────────────────────────────────────────────────────────────────

# Rewards cells contain nested <table><tr>...</tr></table> which breaks naive
# <tr>...</tr> regex splitting (the inner </tr> terminates the outer match early).
# Fix: split the tbody on quest anchor tags instead, then extract levels and
# category from the text that follows each anchor up to the next anchor.
QUEST_A   = re.compile(
    r'<a href="https://ptr\.wowdb\.com/quests/(\d+)-[^"]*">([^<]+)</a>'
    r'(.*?)(?=<a href="https://ptr\.wowdb\.com/quests/\d+|$)',
    re.DOTALL
)
BARE_NUM  = re.compile(r'<td>\s*(\d+)\s*</td>')
BARE_TEXT = re.compile(r'<td>\s*([A-Za-z][A-Za-z0-9 \'\-\:\(\)/]{1,60}?)\s*</td>')

def parse_page(path):
    """Return list of (questID, name, minLevel, maxLevel, category) from one HTML page."""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            html = f.read()
    except Exception as e:
        print(f"  [ERR] Could not read {path.name}: {e}")
        return []

    tbody = re.search(r'<tbody>(.*?)</tbody>', html, re.DOTALL)
    if not tbody:
        return []

    quests = []
    for m in QUEST_A.finditer(tbody.group(1)):
        quest_id = int(m.group(1))
        name     = html_module.unescape(m.group(2).strip())
        rest     = m.group(3)           # everything after </a> up to next quest link

        levels   = BARE_NUM.findall(rest)
        cats     = BARE_TEXT.findall(rest)

        min_level = int(levels[0]) if len(levels) > 0 else 0
        max_level = int(levels[1]) if len(levels) > 1 else min_level
        category  = cats[-1].strip() if cats else ""

        if not name:
            continue

        quests.append((quest_id, name, min_level, max_level, category))
    return quests


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    pages = sorted(HTML_DIR.glob("page_*.html"),
                   key=lambda p: int(re.search(r'page_(\d+)', p.name).group(1)))
    if not pages:
        print(f"No page_*.html files found in {HTML_DIR}")
        sys.exit(1)

    print(f"Found {len(pages)} pages in {HTML_DIR}")
    print("Parsing...")

    all_quests = {}   # questID -> (name, minLevel, maxLevel, category)
    skipped_dup = 0

    for page in pages:
        rows = parse_page(page)
        for (qid, name, mn, mx, cat) in rows:
            if qid not in all_quests:
                all_quests[qid] = (name, mn, mx, cat)
            else:
                skipped_dup += 1

    total = len(all_quests)
    print(f"  {total} unique quests extracted  ({skipped_dup} duplicate IDs skipped)")

    # ── CSV output ───────────────────────────────────────────────────────────
    csv_path = OUTPUT_DIR / "quests_database.csv"
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["questID", "name", "minLevel", "maxLevel", "category"])
        for qid in sorted(all_quests.keys()):
            name, mn, mx, cat = all_quests[qid]
            writer.writerow([qid, name, mn, mx, cat])
    print(f"  CSV  -> {csv_path}")

    # ── Lua output ───────────────────────────────────────────────────────────
    # CA.QuestDB[questID] = { name, minLevel, maxLevel, category }
    # Useful for /caquestscan cross-reference and future guide auto-fill.
    lua_path = OUTPUT_DIR / "quests_database.lua"
    def esc(s):
        return s.replace("\\", "\\\\").replace('"', '\\"')

    with open(lua_path, "w", encoding="utf-8") as f:
        f.write("-- CharacterAdvisor/Data/QuestDB.lua\n")
        f.write("-- Auto-generated by crawl_wowdb_quests.py from WoWDB PTR dump\n")
        f.write(f"-- {total} quests\n")
        f.write("-- DO NOT EDIT BY HAND — regenerate from the HTML dump.\n\n")
        f.write("local CA = CharacterAdvisor\n")
        f.write("CA.QuestDB = CA.QuestDB or {}\n\n")
        f.write("local Q = CA.QuestDB\n\n")
        for qid in sorted(all_quests.keys()):
            name, mn, mx, cat = all_quests[qid]
            f.write(
                f'Q[{qid}] = {{ n="{esc(name)}", mn={mn}, mx={mx}, z="{esc(cat)}" }}\n'
            )
    print(f"  Lua  -> {lua_path}")

    # ── Quick stats ──────────────────────────────────────────────────────────
    print()
    print("Top 20 categories by quest count:")
    from collections import Counter
    cats = Counter(v[3] for v in all_quests.values() if v[3])
    for cat, count in cats.most_common(20):
        print(f"  {count:5d}  {cat}")

    # Level distribution
    print()
    level_dist = Counter()
    for name, mn, mx, cat in all_quests.values():
        level_dist[mn] += 1
    print("Quests by required level (top 15):")
    for lvl, count in sorted(level_dist.most_common(15), key=lambda x: x[0]):
        print(f"  Level {lvl:3d}: {count:5d} quests")

    print()
    print("Done.")


if __name__ == "__main__":
    main()
