#!/usr/bin/env python3
"""
CharacterAdvisor -- Blizzard Quest Data Fetcher
================================================
Replaces crawl_wowdb_quests.py. Pulls quest data straight from Blizzard's
official Game Data API (OAuth client-credentials flow) instead of scraping
a third-party site. Produces the SAME output format as the old WoWDB
crawler (quests_database.csv / quests_database.lua), so gen_midnight_stubs.py
and any other downstream tool keep working unmodified.

Setup
-----
  pip install requests

  Set your client credentials as environment variables (do NOT hardcode
  them in this file or commit them anywhere):

      # PowerShell
      $env:BLIZZARD_CLIENT_ID     = "your-client-id"
      $env:BLIZZARD_CLIENT_SECRET = "your-client-secret"

      # bash
      export BLIZZARD_CLIENT_ID="your-client-id"
      export BLIZZARD_CLIENT_SECRET="your-client-secret"

First run -- verify the schema
-------------------------------
Blizzard's exact JSON field names have shifted across API versions, so
before trusting the bulk extraction, sanity-check one quest:

    python fetch_wow_quests.py --inspect 26866

That dumps the raw JSON for that quest ID. Compare it against the field
names read in `extract_row()` below and adjust if Blizzard's schema
differs from what's assumed here.

Usage
-----
    python fetch_wow_quests.py                  # full index crawl (slow, ~40k+ quests)
    python fetch_wow_quests.py --limit 200       # smoke-test on the first 200 quests
    python fetch_wow_quests.py --ids 26866,26867 # fetch only specific quest IDs
    python fetch_wow_quests.py --resume          # skip IDs already in the output CSV

Rate limiting
-------------
Blizzard's API allows 36,000 requests/hour at up to 100 requests/second.
This script self-throttles well under both limits and backs off on 429s,
per the API Terms of Use ("You may not use the Blizzard Developer APIs
Excessively").
"""

import argparse
import csv
from pathlib import Path

from blizzard_api import add_credential_args, api_get, get_access_token, require_credentials, MIN_INTERVAL

OUTPUT_DIR = Path(r"E:\OneDrive\Desktop\wowdb")   # same location the old crawler used


# ── Quest index / detail ──────────────────────────────────────────────────────

def fetch_quest_index(token):
    print("Fetching quest index...")
    data = api_get("/data/wow/quest/index", token)
    quests = data.get("quests", [])
    print(f"  {len(quests)} quest IDs in index")
    return [q["id"] for q in quests]


def fetch_quest_detail(token, quest_id):
    return api_get(f"/data/wow/quest/{quest_id}", token)


def extract_row(detail):
    """
    Map Blizzard's Quest response onto the same 5-column shape the old
    WoWDB crawler produced: (questID, name, minLevel, maxLevel, category).

    NOTE: field names below are the commonly documented ones as of this
    writing. Run --inspect on a real quest ID and confirm before trusting
    this at scale -- Blizzard has changed quest schema fields before.
    """
    qid  = detail.get("id")
    name = detail.get("title") or detail.get("name") or ""

    req = detail.get("requirements", {}) or {}
    min_level = req.get("min_character_level", 0) or 0
    max_level = req.get("max_character_level", 0) or min_level

    area = detail.get("area", {}) or {}
    category = area.get("name", "")

    return (qid, name, min_level, max_level, category)


# ── Output writers (same format as crawl_wowdb_quests.py) ────────────────────

def write_csv(rows, path, append=False):
    mode = "a" if append and path.exists() else "w"
    write_header = not (append and path.exists())
    with open(path, mode, newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if write_header:
            writer.writerow(["questID", "name", "minLevel", "maxLevel", "category"])
        for row in rows:
            writer.writerow(row)


def write_lua(all_rows, path):
    def esc(s):
        return str(s).replace("\\", "\\\\").replace('"', '\\"')

    with open(path, "w", encoding="utf-8") as f:
        f.write("-- CharacterAdvisor/Data/QuestDB.lua\n")
        f.write("-- Auto-generated by fetch_wow_quests.py from Blizzard's official API\n")
        f.write(f"-- {len(all_rows)} quests\n")
        f.write("-- DO NOT EDIT BY HAND -- regenerate from the API.\n\n")
        f.write("local CA = CharacterAdvisor\n")
        f.write("CA.QuestDB = CA.QuestDB or {}\n\n")
        f.write("local Q = CA.QuestDB\n\n")
        for (qid, name, mn, mx, cat) in all_rows:
            f.write(f'Q[{qid}] = {{ n="{esc(name)}", mn={mn}, mx={mx}, z="{esc(cat)}" }}\n')


def load_existing_ids(csv_path):
    if not csv_path.exists():
        return set()
    with open(csv_path, encoding="utf-8") as f:
        return {int(r["questID"]) for r in csv.DictReader(f)}


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    add_credential_args(ap)
    ap.add_argument("--ids", help="Comma-separated quest IDs to fetch instead of the full index")
    ap.add_argument("--limit", type=int, help="Only process the first N quests from the index (testing)")
    ap.add_argument("--resume", action="store_true", help="Skip quest IDs already present in the output CSV")
    ap.add_argument("--inspect", type=int, metavar="QUEST_ID",
                     help="Fetch and pretty-print the raw JSON for one quest ID, then exit")
    ap.add_argument("--out", default=str(OUTPUT_DIR), help="Output directory")
    args = ap.parse_args()

    require_credentials(args)

    print("Requesting access token...")
    token = get_access_token(args.client_id, args.client_secret)

    if args.inspect is not None:
        import json
        detail = fetch_quest_detail(token, args.inspect)
        print(json.dumps(detail, indent=2, ensure_ascii=False))
        return

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / "quests_database.csv"
    lua_path = out_dir / "quests_database.lua"

    if args.ids:
        quest_ids = [int(x) for x in args.ids.split(",") if x.strip()]
    else:
        quest_ids = fetch_quest_index(token)
        if args.limit:
            quest_ids = quest_ids[: args.limit]

    skip_ids = load_existing_ids(csv_path) if args.resume else set()
    if skip_ids:
        before = len(quest_ids)
        quest_ids = [q for q in quest_ids if q not in skip_ids]
        print(f"Resuming: skipping {before - len(quest_ids)} already-fetched quests")

    print(f"Fetching details for {len(quest_ids)} quests "
          f"(~{len(quest_ids) * MIN_INTERVAL / 60:.1f} min minimum at self-throttled rate)...")

    rows = []
    errors = 0
    for i, qid in enumerate(quest_ids, 1):
        try:
            detail = fetch_quest_detail(token, qid)
            rows.append(extract_row(detail))
        except Exception as e:
            errors += 1
            print(f"  [ERR] quest {qid}: {e}")

        if i % 200 == 0 or i == len(quest_ids):
            print(f"  {i}/{len(quest_ids)} fetched ({errors} errors)")
            # Flush progress incrementally so a Ctrl-C doesn't lose everything
            write_csv(rows, csv_path, append=args.resume)
            rows = []

    if rows:
        write_csv(rows, csv_path, append=args.resume or True)

    # Rebuild the full Lua table from the complete CSV (index + resumed rows)
    all_rows = []
    with open(csv_path, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            all_rows.append((r["questID"], r["name"], r["minLevel"], r["maxLevel"], r["category"]))
    write_lua(all_rows, lua_path)

    print(f"\nDone. CSV -> {csv_path}")
    print(f"      Lua -> {lua_path}")
    print(f"      {errors} errors total")


if __name__ == "__main__":
    main()
