-- Tools/gen_forever_data.lua
--
-- Turns the Forever harvest (ToonAgeDB.foreverHarvest in the saved file) into
-- shipped data files under Data/Forever/, so every player gets what one
-- account measured, without harvesting it themselves.
--
--   lua gen_forever_data.lua <path to WTF\...\SavedVariables\ToonAge.lua> <addon root> [channel]
--
--   channel  beta | live | ptr -- what you know the harvest came from (S3,
--            2026-10-04). Without it the store's recorded channel is used,
--            else "unknown". Never guessed from a realm name.
--
-- Writes:
--   Data/Forever/Racials.lua   race -> faction -> racials (tooltip verbatim,
--                              cooldown and counter tags read from it)
--   Data/Forever/Talents.lua   class -> talent nodes (spell, name, max ranks)
--   Data/Forever/Spells.lua    class -> spells seen in spellbooks (rank text,
--                              trained level, spellbook line)
--   Data/Forever/Items.lua     itemID -> item record with its stat block
--
-- Nothing is invented here. Every value is what the client reported; the only
-- derived fields are the cooldown (read out of the tooltip's own "N min
-- cooldown") and the counter tags (keywords from the tooltip's own wording),
-- and each rule is written out below so it can be checked against the text.
-- Characters (names, GUIDs) are never written out -- they are the player's.
--
-- Deterministic: records are sorted, so regenerating from the same harvest
-- produces byte-identical files and a diff shows only real change.

local svPath, root, channelArg = arg[1], arg[2], arg[3]
assert(svPath and root, "usage: lua gen_forever_data.lua <ToonAge.lua saved file> <addon root> [channel]")

dofile(svPath)
-- The store moved from foreverHarvest to harvest (harvest spec T3); read
-- whichever this save has.
local H = assert(ToonAgeDB and (ToonAgeDB.harvest or ToonAgeDB.foreverHarvest),
    "no harvest store (ToonAgeDB.harvest / .foreverHarvest) in " .. svPath)

-- ── helpers ───────────────────────────────────────────────────────────────

local function Fields(line)
    local f = {}
    for v in (tostring(line) .. "\t"):gmatch("([^\t]*)\t") do f[#f + 1] = v end
    return f
end

local function SortedKeys(t, cmp)
    local k = {}
    for key in pairs(t) do k[#k + 1] = key end
    table.sort(k, cmp or function(a, b) return tostring(a) < tostring(b) end)
    return k
end

local function Q(s) return string.format("%q", tostring(s or "")) end
local function N(v) local n = tonumber(v); return n and tostring(n) or "nil" end

-- The stamp (S3). Each value is what the store recorded; nothing is guessed.
--   interface: the client block, else the character records (their last field
--              is select(4, GetBuildInfo()), the interface number)
--   build:     the client block, else the catalog scan's build
--   channel:   the argument, else the store's recorded channel, else unknown
--   harvested: first .. last write across sections (store v3), else unknown;
--              the first is unknown when records were moved or merged in from
--              foreverHarvest (they carry no write time)
local client = type(H.client) == "table" and H.client or {}
local interfaceNo = client.interface
if interfaceNo == nil then
    for _, line in pairs(H.chars or {}) do
        local f = Fields(line)
        interfaceNo = interfaceNo or tonumber(f[#f])
    end
end
local buildNo = client.build or H.catalogBuild
local channel = (channelArg and channelArg ~= "") and channelArg or client.channel or "unknown"
local harvested = "unknown"
do
    local lo, hi
    for _, t in pairs(type(H.times) == "table" and H.times or {}) do
        if type(t) == "table" then
            if type(t.first) == "number" and (not lo or t.first < lo) then lo = t.first end
            if type(t.last) == "number" and (not hi or t.last > hi) then hi = t.last end
        end
    end
    if client.migratedFrom or client.mergedFrom then lo = nil end
    if hi then
        harvested = (lo and os.date("%Y-%m-%d", lo) or "unknown") .. " .. " .. os.date("%Y-%m-%d", hi)
    end
end

local function Header(file, what, count)
    return table.concat({
        "-- ToonAge/Data/Forever/" .. file,
        "-- GENERATED by Tools/gen_forever_data.lua from the Forever harvest -- do not edit by hand.",
        "--",
        "-- " .. what,
        "-- Measured on the Forever client (interface " .. tostring(interfaceNo or "unknown")
            .. ", build " .. tostring(buildNo or "unknown") .. ", channel " .. tostring(channel)
            .. "; harvested " .. harvested .. "); " .. count .. " records.",
        "-- Regenerate after a harvest: lua Tools/gen_forever_data.lua <ToonAge.lua saved file> <addon root> [channel]",
        "",
        "local TA = ToonAge",
        "TA.Data = TA.Data or {}",
        "",
    }, "\n")
end

local function Write(rel, text)
    local path = root .. "/" .. rel
    local f = assert(io.open(path, "wb"))
    f:write(text)
    f:close()
    print(("wrote %s (%d bytes)"):format(rel, #text))
end

-- ── Racials ───────────────────────────────────────────────────────────────
--
-- Record: name, rank text, "passive"|"", classes seen (comma list), tooltip.
-- Derived, from the tooltip text only:
--   cooldown  "N min cooldown" -> N*60, "N sec cooldown" -> N
--   removes   what the racial clears or blocks ON YOU. Only tagged when the
--             tooltip says it removes / grants immunity / reduces duration on
--             you, so War Stomp ("Stuns up to 5 enemies") is not a stun
--             counter.
--   inflicts  crowd control it applies to OTHERS (War Stomp -> stun)
--   burst     an active racial that "Increases" a stat "for N sec"
-- classes = nil means every class saw the same spell ID; a list means this
-- version is specific to those classes (Gnome Rage/Energy/Mana, Undead's
-- Touch of the Grave 5% vs 10%).

local COUNTER_WORDS = {
    { "stun",    "Stun" },
    { "fear",    "Fear" },
    { "charm",   "Charm" },
    { "sleep",   "Sleep" },
    { "snare",   "movement impairing" },
    { "bleed",   "Bleed" },
    { "poison",  "Poison" },
    { "disease", "Disease" },
    { "curse",   "Curse" },
}

local function RacialTags(tip, passive)
    local t = { removes = {}, inflicts = {} }
    t.cooldown = (tonumber(tip:match("(%d+) min cooldown")) or 0) * 60
    if t.cooldown == 0 then t.cooldown = tonumber(tip:match("(%d+) sec cooldown")) end
    if t.cooldown == 0 then t.cooldown = nil end

    local defensive = tip:find("[Rr]emoves") or tip:find("immunity")
        or tip:find("on you reduced") or tip:find("[Ee]scape the effects")
    for _, w in ipairs(COUNTER_WORDS) do
        if tip:find(w[2], 1, true) then
            if defensive then
                t.removes[#t.removes + 1] = w[1]
            elseif w[1] == "stun" and tip:find("Stuns up to") then
                t.inflicts[#t.inflicts + 1] = "stun"
            end
        end
    end
    if tip:find("stealth detection", 1, true) then t.detects = "stealth" end
    if not passive and tip:find("Increases") and tip:find("for %d+ sec") then
        t.burst = true
    end
    return t
end

local function TagList(list)
    if #list == 0 then return nil end
    local q = {}
    for i, v in ipairs(list) do q[i] = Q(v) end
    return "{ " .. table.concat(q, ", ") .. " }"
end

do
    local byRace, count = {}, 0
    for key, line in pairs(H.racials or {}) do
        local race, faction, id = tostring(key):match("^([^:]+):([^:]+):(%d+)$")
        if race then
            local f = Fields(line)
            byRace[race] = byRace[race] or {}
            byRace[race][faction] = byRace[race][faction] or {}
            table.insert(byRace[race][faction], {
                id = tonumber(id), name = f[1], rank = f[2], passive = f[3] == "passive",
                classes = f[4], tip = f[5] or "",
            })
            count = count + 1
        end
    end

    -- A spell ID seen on one class only, while another ID of the SAME NAME
    -- exists for the race, is class-specific. Otherwise it applies to all.
    local out = { Header("Racials.lua",
        "Racial abilities per race and faction, tooltips verbatim from the client.", count) }
    out[#out + 1] = "TA.Data.ForeverRacials = {"
    for _, race in ipairs(SortedKeys(byRace)) do
        out[#out + 1] = ("    [%s] = {"):format(Q(race))
        for _, faction in ipairs(SortedKeys(byRace[race])) do
            local list = byRace[race][faction]
            local sameName = {}
            for _, r in ipairs(list) do sameName[r.name] = (sameName[r.name] or 0) + 1 end
            table.sort(list, function(a, b)
                if a.name ~= b.name then return a.name < b.name end
                return a.id < b.id
            end)
            out[#out + 1] = ("        [%s] = {"):format(Q(faction))
            for _, r in ipairs(list) do
                local t = RacialTags(r.tip, r.passive)
                local parts = {
                    "id = " .. r.id, "name = " .. Q(r.name),
                }
                if r.passive then parts[#parts + 1] = "passive = true" end
                if sameName[r.name] > 1 then
                    local cl = {}
                    for c in r.classes:gmatch("[^,]+") do cl[#cl + 1] = Q(c) end
                    parts[#parts + 1] = "classes = { " .. table.concat(cl, ", ") .. " }"
                end
                if t.cooldown then parts[#parts + 1] = "cooldown = " .. t.cooldown end
                local rm, inf = TagList(t.removes), TagList(t.inflicts)
                if rm then parts[#parts + 1] = "removes = " .. rm end
                if inf then parts[#parts + 1] = "inflicts = " .. inf end
                if t.detects then parts[#parts + 1] = "detects = " .. Q(t.detects) end
                if t.burst then parts[#parts + 1] = "burst = true" end
                parts[#parts + 1] = "tooltip = " .. Q(r.tip)
                out[#out + 1] = "            { " .. table.concat(parts, ", ") .. " },"
            end
            out[#out + 1] = "        },"
        end
        out[#out + 1] = "    },"
    end
    out[#out + 1] = "}"
    Write("Data/Forever/Racials.lua", table.concat(out, "\n") .. "\n")
end

-- ── Talents ───────────────────────────────────────────────────────────────
-- Key CLASS:T:treeID:nodeID -> treeID, nodeID, entryID, spellID, name,
-- rank (of the character that recorded it; not shipped), maxRanks, level.

do
    local byClass, count = {}, 0
    for key, line in pairs(H.talents or {}) do
        local class = tostring(key):match("^([A-Z]+):T:")
        if class then
            local f = Fields(line)
            byClass[class] = byClass[class] or {}
            table.insert(byClass[class], {
                tree = tonumber(f[1]), node = tonumber(f[2]), entry = tonumber(f[3]),
                spell = tonumber(f[4]), name = f[5], max = tonumber(f[7]),
            })
            count = count + 1
        end
    end
    local out = { Header("Talents.lua",
        "Talent nodes per class: the tree's vocabulary (no builds, no advice).", count) }
    out[#out + 1] = "TA.Data.ForeverTalents = {"
    for _, class in ipairs(SortedKeys(byClass)) do
        local list = byClass[class]
        table.sort(list, function(a, b) return a.node < b.node end)
        out[#out + 1] = ("    [%s] = {"):format(Q(class))
        for _, t in ipairs(list) do
            out[#out + 1] = ("        { tree = %s, node = %s, entry = %s, spell = %s, name = %s, maxRanks = %s },")
                :format(N(t.tree), N(t.node), N(t.entry), N(t.spell), Q(t.name), N(t.max))
        end
        out[#out + 1] = "    },"
    end
    out[#out + 1] = "}"
    Write("Data/Forever/Talents.lua", table.concat(out, "\n") .. "\n")
end

local racialIDs = {}
for key in pairs(H.racials or {}) do
    local id = tonumber(tostring(key):match(":(%d+)$"))
    if id then racialIDs[id] = true end
end

-- ── Spells ────────────────────────────────────────────────────────────────
-- Key CLASS:spellID -> name, first-seen level, spellbook line, rank text,
-- "passive"|"", trained level. Racials are left out (Racials.lua has them,
-- keyed by race). first-seen level is the harvesting character's, not data
-- about the spell, so it is not shipped.

do
    local byClass, count = {}, 0
    for key, line in pairs(H.spells or {}) do
        local class, id = tostring(key):match("^([A-Z]+):(%d+)$")
        if class then
            local f = Fields(line)
            -- Racials are left out by rank text, and by ID for older records
            -- whose rank text was stored blank before the harvester read it.
            if not (f[4] or ""):find("Racial") and not racialIDs[tonumber(id)] then
                byClass[class] = byClass[class] or {}
                table.insert(byClass[class], {
                    id = tonumber(id), name = f[1], line = f[3], rank = f[4],
                    passive = f[5] == "passive", learned = tonumber(f[6]),
                })
                count = count + 1
            end
        end
    end
    local out = { Header("Spells.lua",
        "Class spells seen in spellbooks: rank text and the level each rank is trained.", count) }
    out[#out + 1] = "TA.Data.ForeverSpells = {"
    for _, class in ipairs(SortedKeys(byClass)) do
        local list = byClass[class]
        table.sort(list, function(a, b)
            if a.name ~= b.name then return a.name < b.name end
            return a.id < b.id
        end)
        out[#out + 1] = ("    [%s] = {"):format(Q(class))
        for _, s in ipairs(list) do
            local parts = { "id = " .. s.id, "name = " .. Q(s.name), "line = " .. Q(s.line) }
            if s.rank and s.rank ~= "" then parts[#parts + 1] = "rank = " .. Q(s.rank) end
            if s.learned and s.learned > 0 then parts[#parts + 1] = "learned = " .. s.learned end
            if s.passive then parts[#parts + 1] = "passive = true" end
            out[#out + 1] = "        { " .. table.concat(parts, ", ") .. " },"
        end
        out[#out + 1] = "    },"
    end
    out[#out + 1] = "}"
    Write("Data/Forever/Spells.lua", table.concat(out, "\n") .. "\n")
end

-- ── Items ─────────────────────────────────────────────────────────────────
-- itemID -> name, ilvl, quality, minLevel, classID, subclassID, type, subtype,
-- equipLoc, bindType, "STAT=value,STAT=value".

do
    local out, count = {}, 0
    local ids = {}
    for id in pairs(H.items or {}) do ids[#ids + 1] = tonumber(id) end
    table.sort(ids)
    for _, id in ipairs(ids) do
        local line = H.items[id] or H.items[tostring(id)]
        local f = Fields(line)
        local stats = {}
        for k, v in (f[11] or ""):gmatch("([^=,]+)=([^,]+)") do
            stats[#stats + 1] = ("[%s] = %s"):format(Q(k), N(v))
        end
        out[#out + 1] = ("    [%d] = { name = %s, ilvl = %s, quality = %s, minLevel = %s, classID = %s, subclassID = %s, type = %s, subtype = %s, equipLoc = %s, bind = %s%s },")
            :format(id, Q(f[1]), N(f[2]), N(f[3]), N(f[4]), N(f[5]), N(f[6]), Q(f[7]), Q(f[8]), Q(f[9]), N(f[10]),
                #stats > 0 and (", stats = { " .. table.concat(stats, ", ") .. " }") or "")
        count = count + 1
    end
    table.insert(out, 1, Header("Items.lua",
        "Items seen by the harvest, with the stat block the client reported.", count)
        .. "TA.Data.ForeverItems = {")
    out[#out + 1] = "}"
    Write("Data/Forever/Items.lua", table.concat(out, "\n") .. "\n")
end

-- ── Spell ranks (the catalog) ────────────────────────────────────────────
-- catalog["spellID"] = name, rank text, trained level. Written as
-- name -> entries sorted by TRAINED LEVEL (then ID), the shape
-- Modules/Forever/Rotation.lua reads (TA.Data.ForeverSpellRanks). `n` is the
-- rank number. Only entries WITH rank text are shipped: the client reports a
-- trained level for NPC copies of a spell as well (Fireball 9053, 20823 at
-- "level 20", no rank), so rank text is what marks the player's ranks. The
-- catalog scan re-asks blank ones until the text has loaded.

do
    local byName, count = {}, 0
    for id, line in pairs(H.catalog or {}) do
        local f = Fields(line)
        local n = tonumber((f[2] or ""):match("^Rank (%d+)$"))
        local learned = tonumber(f[3])
        -- Rank text required: NPC copies of a spell report a trained level
        -- too (Fireball 9053: level 20, no rank), rank text separates them.
        if f[1] ~= "" and learned and learned > 0 and n then
            byName[f[1]] = byName[f[1]] or {}
            table.insert(byName[f[1]], { id = tonumber(id), n = n, learned = learned })
            count = count + 1
        end
    end
    -- A name with one entry has no "next rank"; the Spells tab never reads it,
    -- so it is not shipped.
    for name, list in pairs(byName) do
        if #list < 2 then byName[name] = nil; count = count - 1 end
    end
    if count > 0 then
        local out = { Header("SpellRanks.lua",
            "Every trainable spell the client reports, by spell name, ordered by trained level (the Harvest tab's spell catalog).", count) }
        out[#out + 1] = "TA.Data.ForeverSpellRanks = {"
        for _, name in ipairs(SortedKeys(byName)) do
            local list = byName[name]
            table.sort(list, function(a, b)
                if a.learned ~= b.learned then return a.learned < b.learned end
                return a.id < b.id
            end)
            local parts = {}
            for _, r in ipairs(list) do
                parts[#parts + 1] = r.n
                    and ("{ id = %d, n = %d, learned = %d }"):format(r.id, r.n, r.learned)
                    or  ("{ id = %d, learned = %d }"):format(r.id, r.learned)
            end
            out[#out + 1] = ("    [%s] = { %s },"):format(Q(name), table.concat(parts, ", "))
        end
        out[#out + 1] = "}"
        Write("Data/Forever/SpellRanks.lua", table.concat(out, "\n") .. "\n")
    else
        print("no spell catalog in the harvest yet -- SpellRanks.lua not written")
    end
end
