#!/usr/bin/env python3
"""
ToonAge -- API manifest generator
=================================
Scans the addon source for every WoW API it calls and writes Data/ApiManifest.lua.

The point is that the manifest is *measured*, never hand-maintained. .rules.md
already warns about this: a probe command seeded with guesses tells you about the
guesses, not about the client. Regenerate this file whenever call sites change.

What it collects:

  * Namespaced calls   C_Traits.GetNodeInfo, C_QuestLog.GetInfo, ...
  * A curated set of bare globals that are known to differ across clients or to
    have been deprecated in favour of a namespaced form. Collecting *every*
    capitalised global would drown the signal in CreateFrame and GetTime.

Each entry records the files that call it, so a failed probe points straight at
the code that will break rather than just naming a symbol.

Usage:
    python Tools/gen_api_manifest.py
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

from paths import REPO_ROOT, DATA_DIR

OUT = DATA_DIR / "ApiManifest.lua"

SKIP_DIRS = {"Libs", "Archive", "Monk", "Tools", ".git"}

# Namespaced: C_Something.Function
RE_NS = re.compile(r'\bC_([A-Za-z]+)\.([A-Za-z0-9_]+)')

# Bare globals worth probing. Deliberately curated: these are the ones that
# either differ between retail and classic, or that Blizzard has moved into a
# C_ namespace at some point. Everything else is noise.
BARE_GLOBALS = [
    "GetItemInfo", "GetItemInfoInstant", "GetContainerItemLink",
    "GetContainerNumSlots", "GetSpellInfo", "GetSpellCooldown",
    "GetSpellCharges", "IsSpellKnown", "GetNumQuestLogEntries",
    "GetQuestLogTitle", "GetQuestLogIndexByID", "GetTalentInfo",
    "GetSpecialization", "GetSpecializationInfo", "GetAverageItemLevel",
    "GetInventoryItemLink", "UnitAura", "GetProfessions",
    "GetProfessionInfo", "seterrorhandler", "geterrorhandler",
    "hooksecurefunc", "issecretvalue",
]

RE_BARE = re.compile(r'(?<![\w.:])(' + "|".join(BARE_GLOBALS) + r')\s*\(')


def sources(root: Path):
    for p in sorted(root.rglob("*.lua")):
        if any(d in p.parts for d in SKIP_DIRS):
            continue
        # Never scan our own output. Every API name appears in the previous
        # generation as a quoted key, so including it made the manifest
        # self-perpetuating: an API could enter but never leave, and ApiGuard
        # would report it missing forever after the last real call site was
        # removed. That is exactly what happened to C_Traits.GetActiveConfigID
        # -- fixed in f1273c7, still reported missing three commits later,
        # cited to "Data/ApiManifest.lua" as its only call site.
        if p.resolve() == OUT.resolve():
            continue
        yield p


def main():
    root = Path(REPO_ROOT)
    ns_hits = defaultdict(set)
    bare_hits = defaultdict(set)

    for p in sources(root):
        rel = str(p.relative_to(root)).replace("\\", "/")
        text = p.read_text(encoding="utf-8", errors="replace")
        # Strip line comments so a mention in prose is not counted as a call.
        code = "\n".join(re.sub(r'--.*$', '', line) for line in text.split("\n"))

        for m in RE_NS.finditer(code):
            ns_hits["C_%s.%s" % (m.group(1), m.group(2))].add(rel)
        for m in RE_BARE.finditer(code):
            bare_hits[m.group(1)].add(rel)

    lines = []
    w = lines.append
    w("-- ToonAge/Data/ApiManifest.lua")
    w("-- GENERATED by Tools/gen_api_manifest.py -- do not edit by hand.")
    w("--")
    w("-- Every WoW API the addon calls, measured from source. Core/ApiGuard.lua")
    w("-- probes each one at load and reports what is missing on this client.")
    w("--")
    w("-- Regenerate after adding or removing call sites:")
    w("--     python Tools/gen_api_manifest.py")
    w("")
    w("local TA = ToonAge")
    w("TA.Data = TA.Data or {}")
    w("")
    w("-- [\"C_Namespace.Function\"] = { files that call it }")
    w("TA.Data.ApiManifest = {")
    w("    namespaced = {")
    for name in sorted(ns_hits):
        files = ", ".join('"%s"' % f for f in sorted(ns_hits[name]))
        w('        ["%s"] = { %s },' % (name, files))
    w("    },")
    w("    globals = {")
    for name in sorted(bare_hits):
        files = ", ".join('"%s"' % f for f in sorted(bare_hits[name]))
        w('        ["%s"] = { %s },' % (name, files))
    w("    },")
    w("}")
    w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    print("wrote %s" % OUT)
    print("  namespaced APIs : %d" % len(ns_hits))
    print("  bare globals    : %d" % len(bare_hits))
    print("  namespaces      : %d" % len({k.split(".")[0] for k in ns_hits}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
