#!/usr/bin/env python3
"""
ToonAge -- Forever 1.60.1 spellbook and catalog confirmation
=============================================================
Loads the Forever rank, spellbook, racial, and skill data in Lua 5.1.

The level-1 gnome rogue spellbook and catalog confirmed the rogue rank ids.
Mage chains already in the rank file match Era through level 42, so those
rows are verified too. Missing Era ranks above the harvested chains are not
invented. Gnome and undead racials were already measured; troll Rapid
Regeneration and the hunter Gardening skill are the new rows.

Usage:  python3 Tools/test_forever_confirmed.py [-v]
"""
import sys
from pathlib import Path

try:
    from lupa import lua51
except ImportError:
    sys.exit("lupa not installed.  python3 -m pip install --user lupa")

ROOT = Path(__file__).resolve().parent.parent
VERBOSE = "-v" in sys.argv
_results = []

ROGUE = {
    "Sinister Strike": [(1752, 1), (1757, 6)],
    "Eviscerate": [(2098, 1)],
    "Stealth": [(1784, 1)],
    "Backstab": [(53, 4)],
    "Gouge": [(1776, 6)],
    "Throw": [(2764, 1)],
}


def check(name, got, want):
    ok = got == want
    _results.append(ok)
    if VERBOSE or not ok:
        print(f"  {'ok  ' if ok else 'FAIL'}  {name}")
        if not ok:
            print(f"        got:  {got!r}")
            print(f"        want: {want!r}")
    return ok


def load(rel):
    lua = lua51.LuaRuntime(unpack_returned_tuples=True)
    lua.execute("ToonAge = { Data = {} }")
    lua.execute((ROOT / rel).read_text(encoding="utf-8"))
    return lua


def main():
    ranks = load("Data/Forever/SpellRanks.lua")
    text = (ROOT / "Data/Forever/SpellRanks.lua").read_text(encoding="utf-8")
    head = text[:600]
    check("rank file stays a measured harvest",
          "GENERATED by Tools/gen_forever_data.lua" in head
          and "Measured on the Forever client" in head, True)

    summary = ranks.eval(r"""(function()
        local data = ToonAge.Data.ForeverSpellRanks
        local names, records, unverified, above = 0, 0, 0, 0
        for name, chain in pairs(data) do
            names = names + 1
            for _, row in ipairs(chain) do
                records = records + 1
                if row.verified ~= true then unverified = unverified + 1 end
                if type(row.learned) == "number" and row.learned > 42 then
                    above = above + 1
                end
            end
        end
        return names, records, unverified, above
    end)()""")
    check("rank file has the six confirmed rogue names plus the mage chains", summary[0], 26)
    check("rank file record count matches the header", summary[1], 81)
    check("every shipped rank through level 42 is verified", summary[2], 0)
    check("no rank above level 42 was added", summary[3], 0)

    for name, want in ROGUE.items():
        got = ranks.eval(f"""(function()
            local chain = ToonAge.Data.ForeverSpellRanks[{name!r}]
            local parts = {{}}
            for _, row in ipairs(chain) do
                parts[#parts + 1] = row.id .. ":" .. row.learned .. ":" .. tostring(row.verified)
            end
            return table.concat(parts, ",")
        end)()""")
        expect = ",".join(f"{sid}:{learned}:true" for sid, learned in want)
        check(f"{name} ranks", got, expect)

    spells = load("Data/Forever/Spells.lua")
    book = spells.eval(r"""(function()
        local function row(class, id)
            for _, spell in ipairs(ToonAge.Data.ForeverSpells[class]) do
                if spell.id == id then
                    return spell.name .. ":" .. tostring(spell.learned) .. ":" .. tostring(spell.verified)
                end
            end
            return "missing"
        end
        local n, hunterRapid = 0, false
        for _, list in pairs(ToonAge.Data.ForeverSpells) do
            for _, spell in ipairs(list) do
                n = n + 1
                if spell.id == 1260270 then hunterRapid = true end
            end
        end
        return n, hunterRapid,
            row("ROGUE", 1784), row("ROGUE", 1752), row("ROGUE", 2098), row("ROGUE", 2764)
    end)()""")
    check("spellbook stays 94 records", book[0], 94)
    check("rapid regeneration is not a hunter spell", book[1], False)
    check("rogue spellbook has stealth", book[2], "Stealth:1:true")
    check("rogue spellbook sinister strike", book[3], "Sinister Strike:1:true")
    check("rogue spellbook eviscerate", book[4], "Eviscerate:1:true")
    check("rogue spellbook throw", book[5], "Throw:1:true")

    racials = load("Data/Forever/Racials.lua")
    race = racials.eval(r"""(function()
        local function find(race, faction, id)
            for _, row in ipairs(ToonAge.Data.ForeverRacials[race][faction]) do
                if row.id == id then return row end
            end
        end
        local n = 0
        for _, factions in pairs(ToonAge.Data.ForeverRacials) do
            for _, list in pairs(factions) do n = n + #list end
        end
        local mind = find("Gnome", "Alliance", 1259803)
        local eureka = find("Gnome", "Alliance", 1259812)
        local graveM = find("Scourge", "Horde", 1260201)
        local graveP = find("Scourge", "Horde", 1260189)
        local rapid = find("Troll", "Horde", 1260270)
        local function flag(row)
            if not row then return "missing" end
            return tostring(row.name) .. ":" .. tostring(row.passive == true)
                .. ":" .. tostring(row.tooltip == nil)
        end
        return n, flag(mind), flag(eureka), flag(graveM), flag(graveP), flag(rapid),
            eureka and eureka.cooldown or 0
    end)()""")
    check("racial record count", race[0], 45)
    check("gnome expansive mind stays passive", race[1], "Expansive Mind:true:false")
    check("gnome eureka stays active", race[2], "Eureka!:false:false")
    check("gnome eureka keeps its cooldown", race[6], 120)
    check("undead touch of the grave 1260201", race[3], "Touch of the Grave:true:false")
    check("undead touch of the grave 1260189", race[4], "Touch of the Grave:true:false")
    check("troll rapid regeneration stores no invented tooltip", race[5], "Rapid Regeneration:false:true")

    skills = (ROOT / "Data/Forever/ProfessionSkills.lua").read_text(encoding="utf-8")
    check("skill file stays unverified", "unverified = true" in skills, True)
    reader = (ROOT / "Modules/Character/ProfessionSkills.lua").read_text(encoding="utf-8")
    check("skill reader does not name gardening", "Gardening" not in reader and "1278062" not in reader, True)

    passed = sum(_results)
    print(f"[{'OK' if passed == len(_results) else 'FAIL'}] {passed}/{len(_results)} assertions passed.")
    return 0 if passed == len(_results) else 1


if __name__ == "__main__":
    sys.exit(main())
