-- ToonAge/Data/Guides/TAG_Exiles_Reach.lua
-- STUB -- auto-generated by generate_guide_stub.py
-- TODO: fill in zone map ID, coords (/coord), step text.

local TA = ToonAge
TA.GuideData = TA.GuideData or {}

TA.GuideData["exiles_reach"] = {
    id       = "exiles_reach",
    title    = "Exile's Reach: New Player Experience",
    zone     = 1409,   -- Exile's Reach map ID (sub-zones matched via parent walk in AutoSelectGuide)
    minLevel = 1,
    maxLevel = 10,
    steps = {
        -- Step 1
        {
            type    = "quest",
            questID = 59926,
            text    = "Warming Up",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 2
        {
            type    = "quest",
            questID = 90840,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 3
        {
            type    = "quest",
            questID = 59927,
            text    = "Stand Your Ground",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 4
        {
            type    = "quest",
            questID = 59928,
            text    = "Brace for Impact",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 5
        {
            type    = "quest",
            questID = 59929,
            text    = "Murloc Mania",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 6
        {
            type    = "quest",
            questID = 59930,
            text    = "Emergency First Aid",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 7
        {
            type    = "quest",
            questID = 59931,
            text    = "Finding the Lost Expedition",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 8
        {
            type    = "quest",
            questID = 59932,
            text    = "Cooking Meat",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 9
        {
            type    = "quest",
            questID = 59933,
            text    = "Enhanced Combat Tactics",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 10
        {
            type    = "quest",
            questID = 59934,
            text    = "Enhanced Combat Tactics",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 11
        {
            type    = "quest",
            questID = 59935,
            text    = "Northbound",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 12
        {
            type    = "quest",
            questID = 59937,
            text    = "Taming the Wilds",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 13
        {
            type    = "quest",
            questID = 59938,
            text    = "Down with the Quilboar",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 14
        {
            type    = "quest",
            questID = 59939,
            text    = "Forbidden Quilboar Shadow Magic",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 15
        {
            type    = "quest",
            questID = 59940,
            text    = "The Choppy Booster Mk. 5",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 16
        {
            type    = "quest",
            questID = 59941,
            text    = "Re-sizing the Situation",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 17
        {
            type    = "quest",
            questID = 59942,
            text    = "The Re-Deather",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 18
        {
            type    = "quest",
            questID = 59943,
            text    = "The Harpy Problem",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 19
        {
            type    = "quest",
            questID = 59944,
            text    = "The Rescue of Herbert Gloomburst",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 20
        {
            type    = "quest",
            questID = 59945,
            text    = "Harpy Culling",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 21
        {
            type    = "quest",
            questID = 59946,
            text    = "Purge the Totems",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 22
        {
            type    = "quest",
            questID = 59947,
            text    = "Message to Base",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 23
        {
            type    = "quest",
            questID = 59948,
            text    = "Westward Bound",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 24
        {
            type    = "quest",
            questID = 59949,
            text    = "Who Lurks in the Pit",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 25
        {
            type    = "quest",
            questID = 59950,
            text    = "Stocking Up on Supplies",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 26
        {
            type    = "quest",
            questID = 85679,
            text    = "Repair Yourself",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 27
        {
            type    = "quest",
            questID = 59951,
            text    = "A Druid's Form",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 28
        {
            type    = "quest",
            questID = 59952,
            text    = "A Hunter's Trap",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 29
        {
            type    = "quest",
            questID = 59953,
            text    = "Hunting the Stalker",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 30
        {
            type    = "quest",
            questID = 59954,
            text    = "A Mage's Knowledge",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 31
        {
            type    = "quest",
            questID = 59955,
            text    = "The Best Way to Use Sheep",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 32
        {
            type    = "quest",
            questID = 59956,
            text    = "A Monk's Focus",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 33
        {
            type    = "quest",
            questID = 59957,
            text    = "One Last Spar",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 34
        {
            type    = "quest",
            questID = 59958,
            text    = "A Paladin's Service",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 35
        {
            type    = "quest",
            questID = 59961,
            text    = "A Priest's End",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 36
        {
            type    = "quest",
            questID = 59965,
            text    = "Resurrecting the Recruits",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 37
        {
            type    = "quest",
            questID = 59967,
            text    = "A Rogue's End",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 38
        {
            type    = "quest",
            questID = 59968,
            text    = "The Deadliest of Poisons",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 39
        {
            type    = "quest",
            questID = 59002,
            text    = "A Shaman's Duty",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 40
        {
            type    = "quest",
            questID = 59970,
            text    = "A Warlock's Bargain",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 41
        {
            type    = "quest",
            questID = 59971,
            text    = "A Warrior's End",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 42
        {
            type    = "quest",
            questID = 59972,
            text    = "Hjalmar's Final Execution",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 43
        {
            type    = "quest",
            questID = 59975,
            text    = "To Darkmaul Citadel",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 44
        {
            type    = "quest",
            questID = 59978,
            text    = "Right Beneath Their Eyes",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 45
        {
            type    = "quest",
            questID = 59979,
            text    = "Like Ogres to the Slaughter",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 46
        {
            type    = "quest",
            questID = 59980,
            text    = "Catapult Destruction",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 47
        {
            type    = "quest",
            questID = 59981,
            text    = "Controlling their Stones",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 48
        {
            type    = "quest",
            questID = 59984,
            text    = "Dungeon: Darkmaul Citadel",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 49
        {
            type    = "quest",
            questID = 55991,   -- corrected from stale 59985 via in-game /tarecord capture
            text    = "An End to Beginnings",
            coord   = { map = 1409, x = 0.40, y = 0.32 },
        },
        -- Step 50
        {
            type    = "quest",
            questID = 90842,
            text    = "Home Is Where the Hearth Is",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 51
        {
            type    = "quest",
            questID = 90843,
            text    = "Aiding the Dragon Isles",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 52
        {
            type    = "quest",
            questID = 60162,
            text    = "The Art of Taming",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 53
        {
            type    = "quest",
            questID = 60174,
            text    = "The Divine's Shield",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 54
        {
            type    = "quest",
            questID = 60343,
            text    = "Welcome to Orgrimmar",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 55
        {
            type    = "quest",
            questID = 60344,
            text    = "Finding Your Way",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 56
        {
            type    = "quest",
            questID = 60345,
            text    = "License to Ride",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 57
        {
            type    = "quest",
            questID = 60346,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 58
        {
            type    = "quest",
            questID = 60347,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 59
        {
            type    = "quest",
            questID = 60348,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 60
        {
            type    = "quest",
            questID = 60349,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 61
        {
            type    = "quest",
            questID = 60350,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 62
        {
            type    = "quest",
            questID = 60351,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 63
        {
            type    = "quest",
            questID = 60352,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 64
        {
            type    = "quest",
            questID = 60353,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 65
        {
            type    = "quest",
            questID = 60355,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 66
        {
            type    = "quest",
            questID = 60357,
            text    = "What's Your Specialty?",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
        -- Step 67
        {
            type    = "quest",
            questID = 60359,
            text    = "Home Is Where the Hearth Is",
            coord   = { map = 0, x = 0.00, y = 0.00 },  -- TODO: /coord
        },
    },
}
